### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by HosseinJorjani** [fmarotta/kaobook#20] opened 2019-11-18 11:57 UTC
Dear Federico,

I wanted to have the name of the authors and the publication year in the text. I made 3 small changes to the file "kaobook.cls"

\RequirePackage[
    ... deleted stuff ...
	citestyle=numeric-comp,  CHANGED TO citestyle=authoryear,
	bibstyle=numeric,        CHANGED TO bibstyle=authoryear,
	sorting=none,            CHANGED TO sorting=nyt,
    ... deleted stuff ...
]{biblatex}

This gave me the desired effect :-) 

One questions:
Now, it is only the year that is highlighted in green and clickable. 
Is it possible to have an option that makes the author name also highlighted and clickable.

Regards,
Hossein Jorjani

**Comment by fmarotta** [comment] 2019-11-20 23:31
I'm glad you have achieved that. As regards your question, I can point you to this post on tex.SE:
https://tex.stackexchange.com/questions/1687/hyperlink-name-with-biblatex-authoryear

I copied-and-pasted the code from the accepted answer into the file `kaobook.cls`, right at the end of the bibliography section, and the names became highlighted and clickable. Please let me know if this is what you need.

Regards,
Federico

**Comment by fmarotta** [comment] 2019-12-20 13:29
Closing this since the OP communicated me that the problem is solved.

**Closed by fmarotta** 2019-12-20 13:29 UTC
Labels: question
